name: Build and Release APK

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Get commit message
        id: commit
        run: echo "message=$(git log -1 --pretty=%B | head -n 1)" >> $GITHUB_OUTPUT

      - name: Rename APK
        run: |
          mkdir -p release
          cp build/app/outputs/flutter-apk/app-release.apk release/connect-mask-${{ steps.date.outputs.date }}.apk

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.date.outputs.date }}
          name: Release ${{ steps.date.outputs.date }}
          body: |
            **Commit:** ${{ github.sha }}
            **Message:** ${{ steps.commit.outputs.message }}
            **Branch:** ${{ github.ref_name }}
            
            Automatically built APK from commit.
          draft: false
          prerelease: false
          files: release/connect-mask-${{ steps.date.outputs.date }}.apk

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: connect-mask-apk-${{ steps.date.outputs.date }}
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
